version: "3"

services:

  # broker service
  broker:
    build:
      context: "./../broker"
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  # logger service
  logger:
    build:
      context: "./../logger"
      dockerfile: Dockerfile
    restart: always
    env_file:
      - "./../logger/.env"
    deploy:
      mode: replicated
      replicas: 1

  # authenticate service
  auth:
    build:
      context: "./../auth"
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - "./.env"

  # postgresql
  postgres:
    image: "postgres:14.0"
    ports:
      - "54321:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - "./.env"
    volumes:
      - pg_data/:/var/lib/postgresql/data

  # mongo
  mongo:
    image: "mongo:4.2.16-bionic"
    ports:
      - "27017:27017"
    env_file:
      - "./../logger/.env"
      - "./../logger/mongo.env"
    volumes:
      - mongo_data/:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

volumes:
  pg_data:
  mongo_data:
